import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'

import InputGroup from 'react-bootstrap/InputGroup'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faLock, faPaw } from '@fortawesome/free-solid-svg-icons'
import { Navbar } from 'react-bootstrap'
import useWindowDimensions from '../components/useWindowDimensions'

const Edit: NextPage = () => {
    // const { height, width } = useWindowDimensions();
    
    return (
        <div className={styles.container} id="login-home" >
            <Head>
              <title>SDZWA Login Page</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Navbar bg="light">
                <Container>
                    <Button variant="outline-primary" size="sm" href="..">Back</Button>{' '}
                    <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
                </Container>
            </Navbar>
            
            <Container style={{display: 'flex', alignItems: 'center', flexDirection: 'column', height: '90vh'}}>
                    <Form>
                    <Form.Group className="mb-3" controlId="formBasicText">
                        <Form.Label>Sensor Name</Form.Label>
                        <Form.Control type="name" placeholder="Zoo Visitors" />
                        <Form.Text className="text-muted">
                            This is the name that will be used when displaying the sensor.
                        </Form.Text>
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="formBasicText">
                        <Form.Label>Sensor Description</Form.Label>
                        <Form.Control type="desc" placeholder="This data tracks the daily visitor count at the Zoo" />
                        <Form.Text className="text-muted">
                            This is a brief description of the data provided by the sensor.
                        </Form.Text>
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="dataSelectButton">
                        <Form.Label>Data Type</Form.Label>{' '}
                        <Button variant="outline-primary" size="sm">Numeric</Button>{' '}
                        <Button variant="outline-primary" size="sm">Video</Button>{' '}
                        <Button variant="outline-primary" size="sm">Audio</Button>{' '}
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="formBasicText">
                        <Form.Label>Data Source</Form.Label>
                        <Form.Control type="desc" placeholder="" />
                        <Form.Text className="text-muted">
                        This is where data will come from.
                        </Form.Text>
                    </Form.Group>

                    <Form.Group className="mb-3" controlId="formBasicText">
                        <Form.Label>Data Presentation</Form.Label>
                        <Form.Control type="desc" placeholder="" />
                        <Form.Text className="text-muted">
                        This is what the data will look like.
                        </Form.Text>
                    </Form.Group>



                    <Button variant="primary" type="submit" href="..">
                        Submit
                    </Button>
                    </Form> 
            </Container>
        </div>
    )
}

export default Edit