import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from 'react-bootstrap/Navbar'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Area from '../components/Area'
import Link from 'next/link'
import React, { useEffect } from 'react'
import ReactPlayer from 'react-player'
import ReactAudioPlayer from 'react-audio-player';
import { login, register } from '../services/User';
import { fetchUtils } from 'react-admin'


const Home: NextPage = () => {

  useEffect(() => {
    /*register({
      firstName: 'Ahmed',
      lastName: 'Hussaini',
      email: 'ahmed@gmail.com',
      passwordHash: '12345',
      passwordSalt: 'ABCD',   
    });*/
    fetch("http://localhost:5000/api/sensor/id/21", {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJsYWhAZ21haWwuY29tIiwiaWF0IjoxNjU0MTE3NjY1LCJleHAiOjE2NTQxMjQ4NjV9.5Dh87ebJKR_GK1uQRBUFQ2s7Yt-Kx_1aPceLOMuo-YU',
      },
      method: 'PUT',
      body: JSON.stringify({"name": "Sensor2"})
    })
    .then(response => response.json())
    .then(data => console.log(data));
    try {
      /*console.log(register({
        firstName:  "Brandon",
        lastName: "Dalporto",
        email: 'blah@gmail.com',
        password: "12345",
      }));*/
    } catch (e) {
      console.log(e);
    }
    //let loginResponseJson = loginResponse.json();
    //console.log(loginResponse);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>SDZWA Sensor Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bg="light">
        <Container>
          <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
          <Button variant="outline-primary" href="login">Sign Out</Button>
        </Container>
      </Navbar>
      <Container>
        <div style={{float: 'right', margin: 25}}>
        <div style={{ height:300, width:400}}>
        <ReactAudioPlayer
          src=""
          autoPlay
          controls
        />
        </div>

          <div style={{textAlign: 'center'}}>Live Audio</div>
            <div style={{textAlign: 'right'}}><b>Status: </b>
                      <Button variant="warning" size="sm" disabled>
                          Partially Functional
                      </Button>{' '}
            </div>
          <div style={{marginTop: 100, height: 300, width: 400, backgroundColor: '#E6EBEE'}}>
            <div style={{margin: 100, textAlign: 'center'}}><h2>Add New</h2></div>
            <div style={{textAlign: 'center'}}>
                      <Button variant="outline-secondary" size="lg" href="edit_sensor">
                          +
                      </Button>{' '}
            </div>
          </div>

        </div>

        <div style={{ float: 'left', margin: 25}}>
          <Area width={400} height={300} />
          <div style={{textAlign: 'center'}}>Zoo Visitors</div>
            <div style={{textAlign: 'right'}}><b>Status: </b>
                      <Button variant="danger" size="sm" disabled>
                          Offline
                      </Button>{' '}
            </div>
          <div style={{marginTop: 100}}>
          {/*<ReactPlayer height={300} width={400}*/}
          <div style={{textAlign: 'center'}}>Ape Cam</div>
            <div style={{textAlign: 'right'}}><b>Status: </b>
                      <Button variant="success" size="sm" disabled>
                          Good
                      </Button>{' '}
            </div>
          


          
          </div>
          </div>
        </Container>
    </div>
  )
}

export default Home
