import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import InputGroup from 'react-bootstrap/InputGroup'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faLock, faPaw } from '@fortawesome/free-solid-svg-icons'
import { Navbar } from 'react-bootstrap'
import useWindowDimensions from '../components/useWindowDimensions'
import login from '../services/User'


const Login: NextPage = () => {
    const { height, width } = useWindowDimensions();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const authenticate = () => {
        event?.preventDefault();
        const req = {
            email: email,
            password: password,
        };
        try {
            console.log(login(req));
        } catch (e) {
            console.error(e);
        }
    }

    
    return (
        <div className={styles.container} id="login-home" >
            <Head>
              <title>SDZWA Login Page</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Navbar bg="light">
                <Container>
                    <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
                    <Button variant="outline-primary" href="registration">Register</Button>
                </Container>
            </Navbar>
            <Container style={{display: 'flex', alignItems: 'center', flexDirection: 'column', height: '90vh'}}>
                    <h1 style={{flex: 1, marginTop: width > 600 ? '15%' : '35%', textAlign: 'center'}}>Welcome to the SDZWA Sensor Dashboard <FontAwesomeIcon icon={faPaw}/></h1>
                    <Form style={{width: width > 600 ? '50%' : '70%', flex: 1, marginTop: '5%', marginBottom: width > 600 ? '80%' : '100%'}}>
                        <InputGroup className="mb-3">
                            <InputGroup.Text id="email-addon">
                                <FontAwesomeIcon icon={faEnvelope} style={{color: 'royalblue'}}/>
                            </InputGroup.Text>
                            <Form.Control type="email" placeholder="Enter email" value={email} onChange={({target:{value}}) => {setEmail(value)}}/>
                        </InputGroup>
                        <InputGroup className="mb-3">
                            <InputGroup.Text id="pass-addon">
                                <FontAwesomeIcon icon={faLock} style={{color: 'royalblue'}}/>
                            </InputGroup.Text>
                            <Form.Control type="password" placeholder="Password" value={password} onChange={({target:{value}}) => {setPassword(value)}}/>
                        </InputGroup >
                        <div style={{display: 'flex', alignItems: 'center', flexDirection: 'row', width: '100%'}}>
                        <Button onClick={authenticate} variant="primary" type="submit" href=".." style={{flex: 1, marginLeft: '20%', marginRight: '20%', alignItems: 'center', alignSelf: 'center'}}>
                            Login
                        </Button>
                        </div>
                    </Form>
            </Container>
        </div>
    )
}

export default Login