import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import InputGroup from 'react-bootstrap/InputGroup'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faLock, faPaw } from '@fortawesome/free-solid-svg-icons'
import { Navbar } from 'react-bootstrap'


const Login: NextPage = () => {
    return (
        <div className={styles.container} id="login-home" >
            <Head>
              <title>SDZWA Login Page</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Navbar bg="light">
                <Container>
                    <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
                    <Button variant="outline-primary">Register</Button>
                </Container>
            </Navbar>
            <Container className="w-75 d-flex align-items-center justify-content-center" id="login-form-container">
                <Row>
                    <h1>Welcome to the SDZWA Sensor Dashboard <FontAwesomeIcon icon={faPaw}/></h1>
                </Row>
                <Row>
                    <Form>
                        <InputGroup className="mb-3">
                            <InputGroup.Text id="email-addon">
                                <FontAwesomeIcon icon={faEnvelope} style={{color: 'royalblue'}}/>
                            </InputGroup.Text>
                            <Form.Control type="email" placeholder="Enter email" />
                        </InputGroup>
                        <InputGroup className="mb-3">
                            <InputGroup.Text id="pass-addon">
                                <FontAwesomeIcon icon={faLock} style={{color: 'royalblue'}}/>
                            </InputGroup.Text>
                            <Form.Control type="password" placeholder="Password" />
                        </InputGroup>
                        <Row>
                            <Col className="text-center">
                                <Button variant="primary" type="submit">
                                    Login
                                </Button>
                            </Col>
                        </Row> 
                    </Form>
                </Row>
            </Container>
        </div>
    )
}

export default Login