import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import InputGroup from 'react-bootstrap/InputGroup'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faLock, faPaw } from '@fortawesome/free-solid-svg-icons'
import { Navbar } from 'react-bootstrap'
import useWindowDimensions from '../components/useWindowDimensions'

const Registration: NextPage = () => {
    const { height, width } = useWindowDimensions();
    return (
        <div className={styles.container} id="registration-home">
            <Head>
              <title>Registration Page</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar bg="light">
                <Container>
                    <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
                    <Button variant="outline-primary">Login</Button>
                </Container>
            </Navbar>
            <Container style={{display: 'flex', alignItems: 'center', flexDirection: 'column', height: '90vh'}} id="reg-form-container">
                <h1 style={{flex: 1, marginTop: width > 600 ? '15%' : '35%', textAlign: 'center'}}>Welcome to the SDZWA Sensor Dashboard <FontAwesomeIcon icon={faPaw}/></h1>
                <Form style={{width: width > 600 ? '50%' : '70%', flex: 1, marginTop: '5%', marginBottom: width > 600 ? '80%' : '100%'}}>
                    <Form.Group className="mb-3" controlId="firstName">
                        <Form.Control type="text" placeholder="First name" />
                    </Form.Group>
                    <Form.Group className="mb-3" controlId="lastName">    
                        <Form.Control type="text" placeholder="Last name" />
                    </Form.Group>
                    <InputGroup className="mb-3">
                        <InputGroup.Text id="email-addon">
                            <FontAwesomeIcon icon={faEnvelope} style={{color: 'royalblue'}}/>
                        </InputGroup.Text>
                        <Form.Control type="email" placeholder="Enter email" />
                    </InputGroup>
                    <InputGroup className="mb-3">
                        <InputGroup.Text id="pass-addon">
                            <FontAwesomeIcon icon={faLock} style={{color: 'royalblue'}}/>
                        </InputGroup.Text>
                        <Form.Control type="password" placeholder="Password" />
                    </InputGroup>
                    <div style={{display: 'flex', alignItems: 'center', flexDirection: 'row', width: '100%'}}>
                        <Button variant="primary" type="submit" style={{flex: 1, marginLeft: '20%', marginRight: '20%', alignItems: 'center', flexDirection: 'row', width: '100%', alignSelf: 'center'}}>
                            Sign Up
                        </Button>
                    </div>
                </Form>
            </Container>
        </div>
    )
}

export default Registration