import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from 'react-bootstrap/Navbar'
import Container from 'react-bootstrap/Container'
import Button from 'react-bootstrap/Button'
import Area from '../components/Area'
import StatusBarChart from '../components/status_bar_chart'
import { EditButton } from 'react-admin';

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>SDZWA Sensor Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bg="light">
        <Container>
          <Navbar.Brand href="#home">SDZWA Sensor Dashboard</Navbar.Brand>
          
          <Button variant="outline-primary" href="login">Sign Out</Button>
        </Container>
      </Navbar>
      <Container style={{display: 'flex', alignItems: 'center', flexDirection: 'column', height: '90vh'}}>
        <div style={{marginTop: 25}}>
        <h1 style={{flex: 1, textAlign: 'center'}}>Zoo Visitors</h1>
        <div style={{flex: 1, textAlign: 'right'}} > <Button variant="light" href="edit_sensor">Edit</Button></div>
        <Area width={400} height={300} />
        <div style={{display: 'flex', width: '50%'}}>
            <div style={{display: 'flex', width: '25%'}}>
                <div>
                    <b>Type: </b>Numerical/Time Series
                    <br></br>
                    <b>Format:  </b> Line Chart
                    <br></br>
                    <b>Historical Status: </b>
                </div>
                </div>
                <div style={{display: 'flex', marginLeft: '100%'}}>
                    <div>
                    <b>Source: </b> Relational Database
                    <br></br>
                    <b>Status: </b>
                    <Button variant="success" size="sm" disabled>
                        Good
                    </Button>{' '}
                    </div>
                </div>
            </div>
            <StatusBarChart width={400} height={100} />
        </div>
      </Container>
    </div>
  )
}

export default Home
